name: Create Angular app

on:
  workflow_call:
    
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Create Angular App
        run: |
            # Navigate to the directory where you want to create the Angular application
            cd "${{ github.workspace }}"
            
            # Install Angular CLI globally if not already installed
            npm install -g @angular/cli
            
            # Create a new Angular application
            ng new my-angular-app --defaults
            
            # Navigate into the newly created directory
            cd my-angular-app
            
            # Build the Angular application (optional)
            ng build
            
            # Display success message
            echo "Angular application created successfully!"

      - name: Configure Git and GPG
        run: |
            git config --global user.email "paccarini.bar@outlook.com"
            git config --global user.name "p4dr4"
            echo "${{ secrets.GPG_PRIVATE_KEY }}" | base64 --decode | gpg --batch --import
            echo "${{ secrets.GPG_PASSPHRASE }}" > passphrase.txt
            export GPG_TTY=$(tty)

      - name: Create New Branch
        run: git checkout -b master

      - name: Debugging - Print contents of passphrase.txt
        run: cat passphrase.txt
      
      - name: Commit and Push Changes
        run: |
            cd "${{ github.workspace }}/my-angular-app"  # Navigate to the directory of your Angular application
            git add .
            export GPG_TTY=$(tty)
            gpg --batch --pinentry-mode loopback --passphrase-file "${{ github.workspace }}/passphrase.txt" --sign -a -s
            git commit -m "Add Angular application"
            git push origin master
